### ISSUE TITLE
It a shame

### ISSUE THREAD

**Issue by tehface** [swiftyspiffy/KrakenBot2#3]
Its a shame the main things to get said app going are missing.. i'd love to take look through and run it.. but being the noob i am, i'm unable to do so...

so.. how much would it cost me, for one to be made for me?

Just an idea

Cheers :)

**Comment by swiftyspiffy** [comment]
Hi. There's a handful of files that are moved (3 of which are source files). The primary concern has to do with credential related stuff (twitch logins, backend API endpoints etc). The source files have to do with instantiation of objects related to Twitch connections and BurkeBlack.TV connections. One of the files also has to do with how the bot interprets commands from an external source of commands (mod panel) which is important to keep proprietary.

For those reasons, I have to keep those handful of files down. It should be noted, the bot in the public repo is significantly out of date (like 4 months?). 

If you interested in creating your own simple bot, I highly recommend you check out my Twitch library called TwitchLib. It allows for super simple implementation of Twitch chat/whispers and API in a .NET application (C#, VB, ASP, etc.). Here is a link to that: [TwitchLib](https://github.com/swiftyspiffy/TwitchLib)

**Comment by tehface** [comment]
ok great i'll have a looks around, thanks very much
